version: '3.7'

services:
  gateway: 
    build: ../gateway/   
    depends_on:
      - registry
    ports:
        - '8080:8080'
      
  registry: 
     build: .
     ports:
         - '8761:8761'
         
    